spring.application.name=garagem
# Define cores no terminal
spring.output.ansi.enabled=always
# Define path raiz do endpoint
# http://localhost:8080/garagem/algumacoisa
server.servlet.context-path=/garagem   